//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string ProductCount { get; set; }
        public bool NewOrOld { get; set; }
        public int CategoryID { get; set; }
        public int FirmID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Firm Firm { get; set; }
    }
}
